import React, { useState } from 'react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import '../styling/exportshare.css';

interface ExportShareProps {
    song: {
        title: string;
        artist: string;
        id: string;
    };
    features: any;
    insights?: string[];
}

const ExportShare: React.FC<ExportShareProps> = ({ song, features, insights }) => {
    const [isExporting, setIsExporting] = useState(false);
    const [exportType, setExportType] = useState<'pdf' | 'image' | 'json' | 'text'>('pdf');

    const generatePDFReport = async () => {
        setIsExporting(true);
        try {
            const pdf = new jsPDF();

            // Title
            pdf.setFontSize(20);
            pdf.text(`Music Analysis Report`, 20, 30);

            // Song Info
            pdf.setFontSize(16);
            pdf.text(`Song: ${song.title}`, 20, 50);
            pdf.text(`Artist: ${song.artist}`, 20, 65);

            // Features
            pdf.setFontSize(14);
            pdf.text('Audio Features:', 20, 85);

            let yPosition = 100;
            Object.entries(features).forEach(([key, value]) => {
                const formattedValue = typeof value === 'number' ? value.toFixed(2) : value;
                pdf.setFontSize(12);
                pdf.text(`${key}: ${formattedValue}`, 25, yPosition);
                yPosition += 15;
            });

            // Insights
            if (insights && insights.length > 0) {
                yPosition += 10;
                pdf.setFontSize(14);
                pdf.text('AI Insights:', 20, yPosition);
                yPosition += 15;

                insights.forEach((insight) => {
                    pdf.setFontSize(10);
                    const lines = pdf.splitTextToSize(insight, 170);
                    pdf.text(lines, 25, yPosition);
                    yPosition += lines.length * 5 + 10;

                    if (yPosition > 270) {
                        pdf.addPage();
                        yPosition = 20;
                    }
                });
            }

            pdf.save(`${song.title}-analysis-report.pdf`);
        } catch (error) {
            console.error('Error generating PDF:', error);
        } finally {
            setIsExporting(false);
        }
    };

    const exportAsImage = async () => {
        setIsExporting(true);
        try {
            const element = document.querySelector('.in-depth-analysis-container');
            if (element) {
                const canvas = await html2canvas(element as HTMLElement);
                const link = document.createElement('a');
                link.download = `${song.title}-analysis.png`;
                link.href = canvas.toDataURL();
                link.click();
            }
        } catch (error) {
            console.error('Error exporting image:', error);
        } finally {
            setIsExporting(false);
        }
    };

    const exportAsJSON = () => {
        const data = {
            song: {
                title: song.title,
                artist: song.artist,
                id: song.id
            },
            features,
            insights,
            exportedAt: new Date().toISOString(),
            exportedBy: 'TuneSift'
        };

        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = `${song.title}-analysis-data.json`;
        link.click();
    };

    const exportAsText = () => {
        let content = `MUSIC ANALYSIS REPORT\n`;
        content += `========================\n\n`;
        content += `Song: ${song.title}\n`;
        content += `Artist: ${song.artist}\n\n`;
        content += `AUDIO FEATURES:\n`;
        content += `---------------\n`;

        Object.entries(features).forEach(([key, value]) => {
            const formattedValue = typeof value === 'number' ? value.toFixed(2) : value;
            content += `${key}: ${formattedValue}\n`;
        });

        if (insights && insights.length > 0) {
            content += `\nAI INSIGHTS:\n`;
            content += `------------\n`;
            insights.forEach((insight, index) => {
                content += `${index + 1}. ${insight}\n\n`;
            });
        }

        content += `\nGenerated by TuneSift on ${new Date().toLocaleDateString()}\n`;

        const blob = new Blob([content], { type: 'text/plain' });
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = `${song.title}-analysis.txt`;
        link.click();
    };

    const shareToSocial = (platform: 'twitter' | 'facebook' | 'linkedin') => {
        const text = `Just analyzed "${song.title}" by ${song.artist} with TuneSift! 🎵 Check out these insights: Energy: ${(features.energy * 100).toFixed(0)}%, Danceability: ${(features.danceability * 100).toFixed(0)}%, Mood: ${(features.valence * 100).toFixed(0)}% positive`;
        const url = window.location.href;

        let shareUrl = '';
        switch (platform) {
            case 'twitter':
                shareUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`;
                break;
            case 'facebook':
                shareUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`;
                break;
            case 'linkedin':
                shareUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`;
                break;
        }

        window.open(shareUrl, '_blank', 'width=600,height=400');
    };

    const copyToClipboard = async () => {
        const text = `"${song.title}" by ${song.artist} - Music Analysis:\nEnergy: ${(features.energy * 100).toFixed(0)}%\nDanceability: ${(features.danceability * 100).toFixed(0)}%\nMood: ${(features.valence * 100).toFixed(0)}% positive\n\nAnalyzed with TuneSift`;

        try {
            await navigator.clipboard.writeText(text);
            alert('Analysis copied to clipboard!');
        } catch (error) {
            console.error('Failed to copy:', error);
        }
    };

    const handleExport = () => {
        switch (exportType) {
            case 'pdf':
                generatePDFReport();
                break;
            case 'image':
                exportAsImage();
                break;
            case 'json':
                exportAsJSON();
                break;
            case 'text':
                exportAsText();
                break;
        }
    };

    return (
        <div className="export-share-container">
            <div className="export-share-header">
                <h3>
                    <span className="export-icon">📤</span>
                    Export & Share
                </h3>
            </div>

            <div className="export-section">
                <h4>Export Analysis</h4>
                <div className="export-options">
                    <div className="export-type-selector">
                        {[
                            { type: 'pdf', label: 'PDF Report', icon: '📄' },
                            { type: 'image', label: 'Screenshot', icon: '🖼️' },
                            { type: 'json', label: 'Raw Data', icon: '📊' },
                            { type: 'text', label: 'Text File', icon: '📝' }
                        ].map(option => (
                            <button
                                key={option.type}
                                className={`export-type-btn ${exportType === option.type ? 'active' : ''}`}
                                onClick={() => setExportType(option.type as never)}
                            >
                                <span className="option-icon">{option.icon}</span>
                                <span>{option.label}</span>
                            </button>
                        ))}
                    </div>

                    <button
                        className="export-btn"
                        onClick={handleExport}
                        disabled={isExporting}
                    >
                        {isExporting ? (
                            <>
                                <span className="loading-spinner"></span>
                                Exporting...
                            </>
                        ) : (
                            <>
                                <span className="btn-icon">💾</span>
                                Export {exportType.toUpperCase()}
                            </>
                        )}
                    </button>
                </div>
            </div>

            <div className="share-section">
                <h4>Share Analysis</h4>
                <div className="share-options">
                    <button
                        className="share-btn twitter"
                        onClick={() => shareToSocial('twitter')}
                    >
                        <span className="share-icon">🐦</span>
                        Twitter
                    </button>

                    <button
                        className="share-btn facebook"
                        onClick={() => shareToSocial('facebook')}
                    >
                        <span className="share-icon">📘</span>
                        Facebook
                    </button>

                    <button
                        className="share-btn linkedin"
                        onClick={() => shareToSocial('linkedin')}
                    >
                        <span className="share-icon">💼</span>
                        LinkedIn
                    </button>

                    <button
                        className="share-btn copy"
                        onClick={copyToClipboard}
                    >
                        <span className="share-icon">📋</span>
                        Copy Link
                    </button>
                </div>
            </div>

            <div className="quick-share-preview">
                <h4>Quick Share Preview</h4>
                <div className="share-preview-card">
                    <div className="preview-content">
                        <h5>"{song.title}" by {song.artist}</h5>
                        <div className="preview-stats">
                            <span>Energy: {(features.energy * 100).toFixed(0)}%</span>
                            <span>Danceability: {(features.danceability * 100).toFixed(0)}%</span>
                            <span>Mood: {(features.valence * 100).toFixed(0)}% positive</span>
                        </div>
                        <p className="preview-footer">Analyzed with TuneSift 🎵</p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ExportShare;
